#!/bin/bash

echo ""
echo "#   Installing Latest OwnCloud and Dependencies    #"
echo ""

ask() {
    # http://djm.me/ask
    local prompt default REPLY

    while true; do

        if [ "${2:-}" = "Y" ]; then
            prompt="Y/n"
            default=Y
        elif [ "${2:-}" = "N" ]; then
            prompt="y/N"
            default=N
        else
            prompt="y/n"
            default=
        fi

        # Ask the question (not using "read -p" as it uses stderr not stdout)
        echo "$1 [$prompt] "

        # Read the answer (use /dev/tty in case stdin is redirected from somewhere else)
        read REPLY </dev/tty

        # Default?
        if [ -z "$REPLY" ]; then
            REPLY=$default
        fi

        # Check if the reply is valid
        case "$REPLY" in
            Y*|y*) return 0 ;;
            N*|n*) return 1 ;;
        esac

    done
}

PKG_NAME=php7.0-mbstring
PKG_OK=$(dpkg-query -W --showformat='${Status}\n' $PKG_NAME|grep "install ok installed")
echo Checking for $PKG_NAME: $PKG_OK
if [ "" == "$PKG_OK" ]; then
  echo "No $PKG_NAME. Setting up $PKG_NAME."
  sudo apt --yes install $PKG_NAME
fi

PKG_NAMEphp-imagick
PKG_OK=$(dpkg-query -W --showformat='${Status}\n' $PKG_NAME|grep "install ok installed")
echo Checking for $PKG_NAME: $PKG_OK
if [ "" == "$PKG_OK" ]; then
  echo "No $PKG_NAME. Setting up $PKG_NAME."
  sudo apt --yes install $PKG_NAME
fi

PKG_NAME=php7.0-intl
PKG_OK=$(dpkg-query -W --showformat='${Status}\n' $PKG_NAME|grep "install ok installed")
echo Checking for $PKG_NAME: $PKG_OK
if [ "" == "$PKG_OK" ]; then
  echo "No $PKG_NAME. Setting up $PKG_NAME."
  sudo apt --yes install $PKG_NAME
fi

curl https://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/Release.key | sudo apt-key add -
echo 'deb https://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/ /' | sudo tee /etc/apt/sources.list.d/owncloud.list

apt update

apt --yes install owncloud

echo ""
echo "#       Creating OWNCLOUD User and Database        #"
echo ""

# Getting or Setting OwnCloud Database Name
if grep -q OWNCLOUD_DATABASE /root/.digitalocean_password; then
  echo -e "It looks like you have already set up your database in MySQL. Getting that info now..."
  OWNCLOUD_DATABASE=$(grep OWNCLOUD_DATABASE /root/.digitalocean_password | sed 's#"##g' | sed 's#OWNCLOUD_DATABASE=##g')
else
  echo -e "Setting new OwnCloud Database User and Password in MySQL"
  OWNCLOUD_DATABASE=owncloud
  echo "OWNCLOUD_DATABASE=$OWNCLOUD_DATABASE" >> /root/.digitalocean_password
fi
export OWNCLOUD_DATABASE

# Getting or Setting  OWNCLOUD Database User
if grep -q OWNCLOUD_DB_USER /root/.digitalocean_password; then
  OWNCLOUD_DB_USER=$(grep OWNCLOUD_DB_USER /root/.digitalocean_password | sed 's#"##g' | sed 's#OWNCLOUD_DB_USER=##g')
else
  OWNCLOUD_DB_USER=owncloud
  echo "OWNCLOUD_DB_USER=$OWNCLOUD_DB_USER" >> /root/.digitalocean_password
fi
export OWNCLOUD_DB_USER

# Getting or Setting OWNCLOUD Database Random Password
if grep -q OWNCLOUD_DB_PASSWORD /root/.digitalocean_password; then
  OWNCLOUD_DB_PASSWORD=$(grep OWNCLOUD_DB_PASSWORD /root/.digitalocean_password | sed 's#"##g' | sed 's#OWNCLOUD_DB_PASSWORD=##g')
else
  OWNCLOUD_DB_PASSWORD=$(date +%s | sha256sum | base64 | head -c 32)
  echo "OWNCLOUD_DB_PASSWORD=$OWNCLOUD_DB_PASSWORD" >> /root/.digitalocean_password
fi
export OWNCLOUD_DB_PASSWORD

echo -e "--------------------"
echo -e "You can find your OwnCloud Database Username and Password in /root/.digitalocean_password"
echo -e "--------------------"


mysql -uroot -e "CREATE DATABASE IF NOT EXISTS $OWNCLOUD_DATABASE;"
echo "Database \"$OWNCLOUD_DATABASE\" created"
mysql -uroot -e "CREATE USER IF NOT EXISTS '$OWNCLOUD_DB_USER'@'localhost' IDENTIFIED BY '$OWNCLOUD_DB_PASSWORD';"
echo "User \"$OWNCLOUD_DB_USER\" created @localhost with password \"$OWNCLOUD_DB_PASSWORD\""
mysql -uroot -e "GRANT ALL PRIVILEGES ON $OWNCLOUD_DATABASE.* TO '$OWNCLOUD_DB_USER'@'localhost';"
echo "Granting all privileges on \"$OWNCLOUD_DATABASE\" to '$OWNCLOUD_DB_USER'@'localhost'"
mysql -uroot -e "FLUSH PRIVILEGES;"

echo "Finished OwnCloud Database setup successfully"

DATA_LOCATION="/var/www/owncloud/data"

echo ""
echo "Did you create a \'Volume\' on DigitalOcean that you would like to use for OwnCloud Storage?"
if ask "Please Type [Y] or [N] and the press [enter]: " ; then
  install-files/connectvolume
  install-files/moveowncloud
fi

INSTALL_LOC="/var/www/owncloud"

DO-ssl-setup/sslsetup

echo "Successfully installed and Set up OwnCloud!"


echo ""
echo "Here is your OwnCloud Installation Information. PLEASE WRITE THIS DOWN IN A SECURE LOCATION!"
echo ""
echo "............................."
echo "OwnCloud Installation Location: /var/www/owncloud"
echo "OwnCloud Data Location: $DATA_LOCATION"
echo "OwnCloud Database User: owncloud"
echo "OwnCloud Database Password: $OWNCLOUD_DB_PASSWORD"
echo "OwnCloud Database Name: owncloud"
echo "OwnCloud Database Host: localhost"
echo "............................."
