#!/bin/bash

echo ""
echo "#   Moving OwnCloud Files to Attached Volume    #"
echo ""

echo -e "Stopping Apache server to move your Owncloud Data"
systemctl stop apache2

VOLUME_NAME=$(ls /dev/disk/by-id | awk -F 'DO_Volume_' '{print $2}')
export VOLUME_NAME

echo -e "Moving your Data to /mnt/$VOLUME_NAME"
mkdir /mnt/$VOLUME_NAME/owncloud
mv /var/www/owncloud/data /mnt/$VOLUME_NAME/owncloud

echo -e "Starting Apache Server again"
systemctl start apache2

echo -e "I have successfully moved your data to the Connected Volume!"
